# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GT_Crime_Logs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GT_Crime_Logs

  pod 'SwiftSoup'
  pod 'Alamofire'
  pod 'SwiftCSVExport'
  pod 'SwiftLoggly'

  target 'GT_Crime_LogsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GT_Crime_LogsUITests' do
    # Pods for testing
  end

end
